# Generated by Django 3.0.4 on 2020-03-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
