# Generated by Django 3.0.4 on 2020-03-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200318_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
